name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:

    - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@191986574c0735ffad7ae1a297a414d6e6f95375
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        # Remote host
        REMOTE_HOST: hindung.cn
        # Remote user
        REMOTE_USER: root
        ARGS: "-rltgoDzvO --delete"

    - name: git pull
      run: |
        cd /root/Blog-Backend
        git pull
