name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      # You may pin to the exact commit or the version.
      # uses: appleboy/ssh-action@bf84735fa9986d048980965656d55112e863f432
      uses: appleboy/ssh-action@v0.1.3
      with:
        # ssh host
        host: hindung.cn
        # synchronous execution if multiple hosts
        # timeout for ssh to host
        key: ${{secrets.SERVER_SSH_KEY}}
        script: |
          sudo su
          cd /root/Blog-Backend
          git pull


