name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:

    - name: SSH command runner
      # You may pin to the exact commit or the version.
      # uses: Evaneos/ssh-action@0e5f8933569a924cad91d22e30f7ecfb5d8426f2
      uses: Evaneos/ssh-action@v0.1.0
      with:
        # Remote host(s) to connect to
        hosts: hindung.cn
        # One or multiple commands to run on the remote host(s)
        commands: |
          sudo su
          cd /root/Blog-Backend
          git pull
        # Remote user to connect with
        user: root
        # Remote port to connect to
        port: 22
        # Private SSH key to connect with
        private_key: ${{secrets.SERVER_SSH_KEY}}

